# Generated by Django 4.1.3 on 2022-11-08 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateField(auto_now_add=True,
                                   default=django.utils.timezone.now,
                                   verbose_name='date_of_transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.TimeField(auto_now_add=True, verbose_name='time_of_transaction'),
        ),
    ]
