# Generated by Django 4.1.3 on 2022-11-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money_manager', '0002_transaction_date_of_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_manager.category'),
        ),
    ]
