# Generated by Django 4.1.3 on 2022-11-09 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_manager', '0003_category_total_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateField(default=datetime.date(2022, 11, 9), verbose_name='date_of_transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.TimeField(default=datetime.time(12, 47, 35, 993289), verbose_name='time_of_transaction'),
        ),
    ]
