# Generated by Django 4.1.3 on 2022-11-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_manager', '0006_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.TimeField(default='17:01', verbose_name='time_of_transaction'),
        ),
    ]
