# Generated by Django 4.1.3 on 2022-11-12 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_manager', '0007_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateField(default=datetime.date(2022, 11, 12), verbose_name='date_of_transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.TimeField(default='15:17', verbose_name='time_of_transaction'),
        ),
    ]
