# Generated by Django 4.1.3 on 2022-11-14 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_manager', '0008_alter_transaction_date_of_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateField(default=datetime.date(2022, 11, 14), verbose_name='date_of_transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.TimeField(default='17:18', verbose_name='time_of_transaction'),
        ),
    ]
