# Generated by Django 4.1.3 on 2022-11-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_manager', '0011_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.TimeField(default='10:36', verbose_name='time_of_transaction'),
        ),
    ]
